Pasos para la instalacion de "Docker" en ubuntu 22.04

Primero, actualice su lista existente de paquetes:

    sudo apt update

A continuación, instale algunos paquetes de requisitos previos que permitan aptusar paquetes a través de HTTPS:

    sudo apt install apt-transport-https ca-certificates curl software-properties-common

Luego agregue la clave GPG para el repositorio oficial de Docker a su sistema:

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

Agregue el repositorio de Docker a las fuentes APT:

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

Actualice su lista existente de paquetes nuevamente para que se reconozca la adición:

    sudo apt update

Asegúrese de que está a punto de realizar la instalación desde el repositorio de Docker en lugar del repositorio predeterminado de Ubuntu:

    apt-cache policy docker-ce

Verá un resultado como este, aunque el número de versión de Docker puede ser diferente:

    docker-ce:
    Installed: (none)
    Candidate: 5:20.10.14~3-0~ubuntu-jammy
    Version table:
     5:20.10.14~3-0~ubuntu-jammy 500
        500 https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
     5:20.10.13~3-0~ubuntu-jammy 500
        500 https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages

Observe que docker-ceno está instalado, pero el candidato para la instalación es del repositorio de Docker para Ubuntu 22.04 ( jammy).

Finalmente, instale Docker:

    sudo apt install docker-ce

Ahora Docker debería estar instalado, el demonio iniciado y el proceso habilitado para iniciarse en el arranque. Comprueba que esté funcionando:

    sudo systemctl status docker

El resultado debería ser similar al siguiente, mostrando que el servicio está activo y ejecutándose:

    Output
    ● docker.service - Docker Application Container Engine
        Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
        Active: active (running) since Fri 2022-04-01 21:30:25 UTC; 22s ago
     TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
      Main PID: 7854 (dockerd)
       Tasks: 7
      Memory: 38.3M
        CPU: 340ms
      CGroup: /system.slice/docker.service
             └─7854 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
